/**
 * Agent and system status type definitions for the BeeGame frontend.
 *
 * This file defines types for Agent status tracking, system monitoring,
 * and activity records (artifacts generated by agents).
 */

/**
 * Agent status enumeration
 * Defines the possible states an agent can be in
 */
export type AgentStatus = 'idle' | 'active' | 'working';

/**
 * Agent interface
 * Represents a single agent in the multi-agent system
 */
export interface Agent {
  /** Unique identifier for the agent (e.g., 'logos', 'metis', 'tecton') */
  id: string;

  /** Current status of the agent */
  status: AgentStatus;

  /** Description of the current task the agent is working on (optional) */
  current_task?: string;
}

/**
 * System status interface
 * Represents the overall system health and runtime information
 */
export interface SystemStatus {
  /** System uptime as a formatted string (e.g., "2h 30m") */
  uptime: string;

  /** Whether Unity is currently connected to the system */
  unity_connected: boolean;

  /** Number of agents currently active/working */
  active_agents: number;

  /** Current project progress as a percentage (0-100) */
  project_progress: number;

  /** Runtime-advertised UI capabilities. Specific feature flags are owned by their feature modules. */
  capabilities?: Record<string, unknown>;
}

/**
 * Activity type enumeration
 * Defines the different types of artifacts that can be generated
 */
export type ActivityType = 'code' | 'document' | 'asset';

/**
 * Activity interface
 * Represents a single activity record (artifact) generated by an agent
 */
export interface Activity {
  /** Unique identifier for the activity */
  id: string;

  /** Type of artifact generated */
  type: ActivityType;

  /** Name of the artifact */
  name: string;

  /** Agent that created this artifact */
  author: string;

  /** Timestamp when the artifact was created (Unix timestamp in milliseconds) */
  timestamp: number;
}

export interface TaskCandidateAgent {
  agent_id: string;
  claim_score: number;
  claimability_reason?: string;
  matching_capabilities?: string[];
}

export interface AgentTaskLifecycle {
  task_id: string;
  status: string;
  phase?: string;
  priority?: number;
  summary?: string;
  claim_score?: number;
  claimability_reason?: string;
  candidate_agents?: TaskCandidateAgent[];
  suggested_agents?: string[];
  verification_stage?: string | null;
  invalidated_reason?: string | null;
  artifact_versions?: Array<{
    artifact_id: string;
    artifact_type: string;
    version: number;
  }>;
}
