/**
 * System store for managing system status, agents, activities, and token usage
 * 
 * This store handles:
 * - System status state management (uptime, Unity connection, etc.)
 * - Agent list and status tracking
 * - Activity records (artifacts generated by agents)
 * - Token usage accumulation and tracking
 * 
 * Requirements: 2.1, 4.1, 4.3, 5.1
 */

import { create } from 'zustand';
import type { Agent, SystemStatus, Activity, TaskCandidateAgent } from '../types/agent';
import type { TokenUsage } from '../types/message';
import { api } from '../services/api';
import type {
  BeeGameCurrentUser,
  BeeGamePermission,
} from '../services/currentUserApi';

export interface PhaseInfo {
  current_phase: number;
  phase_name: string;
  history: Array<{
    phase: number;
    name: string;
    timestamp: number;
  }>;
}

export interface ProjectTask {
  id: string;
  status: string;
  task_status: string;
  lifecycle_status?: string;
  summary: string;
  assignee: string | null;
  phase: string | null;
  depends_on: string[];
  updated_at: number;
  priority?: number | null;
  claim_score?: number | null;
  claimability_reason?: string | null;
  candidate_agents?: TaskCandidateAgent[];
  suggested_agents?: string[];
  review_stage?: string | null;
  verification_stage?: string | null;
  invalidated_reason?: string | null;
  artifact_versions?: Array<{
    artifact_id: string;
    artifact_type: string;
    version: number;
  }>;
  execution_mode?: string | null;
  swarm_parent?: string | null;
  micro_swarm_id?: string | null;
  micro_swarm_specialist?: string | null;
  micro_swarm_agents?: string[];
}

/**
 * System store state interface
 */
interface SystemState {
  /** Current system status information */
  status: SystemStatus | null;

  /** List of all agents in the system */
  agents: Agent[];

  /** List of activity records (artifacts) */
  activities: Activity[];

  /** Token usage statistics per project */
  tokenUsage: Record<string, TokenUsage>;

  /** Task-specific token usage tracking to prevent double counting */
  taskUsage: Record<string, TokenUsage>;

  /** Current BeeGame user and permission snapshot */
  currentUser: BeeGameCurrentUser | null;

  /** Whether a synchronization (resync) is in progress */
  isSyncing: boolean;

  /** Loading state for async operations */
  isLoading: boolean;

  /** Team OS telemetry phase tracking */
  phaseInfo: PhaseInfo | null;

  /** List of all work packages/tasks for the project */
  tasks: ProjectTask[];

  /**
   * Load system status from the backend
   */
  loadStatus: () => Promise<void>;

  /**
   * Load current BeeGame user and role permissions.
   */
  loadCurrentUser: () => Promise<BeeGameCurrentUser | null>;

  /**
   * Check whether the current user has a named permission.
   */
  hasPermission: (permission: BeeGamePermission) => boolean;

  /**
   * Load all agents and their current status from the backend
   */
  loadAgents: () => Promise<void>;

  /**
   * Load activity records from the backend
   */
  loadActivities: () => Promise<void>;

  /**
   * Load phase history from backend (Team OS Telemetry)
   */
  loadPhases: (projectId: string) => Promise<void>;

  /**
   * Load all tasks for a project
   */
  loadTasks: (projectId: string) => Promise<void>;

  /**
   * Load cumulative token usage for a project
   */
  loadTokenUsage: (projectId: string) => Promise<void>;

  /** Last detected P2P routing event */
  lastP2PRoute: { source_agent: string; target_agent: string; timestamp: number } | null;

  /** Theme state */
  isDark: boolean;

  /**
   * Update token usage with cumulative calculation (project and task aware)
   */
  updateTokenUsage: (usage: TokenUsage, projectId: string, taskId?: string) => void;

  /**
   * Update the last detected P2P routing event
   */
  updateLastP2PRoute: (route: { source_agent: string; target_agent: string; timestamp: number } | null) => void;

  /**
   * Set the synchronization state
   */
  setIsSyncing: (isSyncing: boolean) => void;

  /**
   * Manually set an agent's status (used for real-time WebSocket updates)
   */
  setAgentStatus: (agentId: string, status: 'idle' | 'working', currentTask?: string) => void;

  /**
   * Refreshes the agent list from the backend (alias for loadAgents)
   */
  refreshAgents: () => Promise<void>;

  /**
   * Toggle global theme
   */
  toggleTheme: () => void;
}


import { createJSONStorage, persist } from 'zustand/middleware';

export const useSystemStore = create<SystemState>()(
  persist(
    (set, get) => ({
      status: null,
      agents: [],
      activities: [],
      tokenUsage: {},
      isLoading: false,
      isSyncing: false,
      phaseInfo: null,
      isDark: true, // Default to dark mode

      tasks: [],
      taskUsage: {},
      currentUser: null,
      lastP2PRoute: null,

      loadCurrentUser: async () => {
        try {
          const currentUser = await api.getCurrentUser();
          set({ currentUser });
          return currentUser;
        } catch (error) {
          console.error('Failed to load current user:', error);
          set({ currentUser: null });
          return null;
        }
      },

      hasPermission: (permission: BeeGamePermission) => (
        Boolean(get().currentUser?.permissions.includes(permission))
      ),

      loadStatus: async () => {
        try {
          set({ isLoading: true });
          const status = (await api.getStatus()) as unknown as SystemStatus;
          set({ status, isLoading: false });
        } catch (error) {
          console.error('Failed to load system status:', error);
          set({ isLoading: false });
          throw error;
        }
      },

      loadAgents: async () => {
        try {
          set({ isLoading: true });
          const agents = (await api.getAgents({ headers: { 'Hide-Error-Toast': 'true' } })) as unknown as Agent[];
          set({ agents, isLoading: false });
        } catch (error) {
          console.error('Failed to load agents:', error);
          set({ isLoading: false });
          throw error;
        }
      },

      loadActivities: async () => {
        try {
          set({ isLoading: true });
          const activities = (await api.getActivity()) as unknown as Activity[];
          set({ activities, isLoading: false });
        } catch (error) {
          console.error('Failed to load activities:', error);
          set({ isLoading: false });
          throw error;
        }
      },

      loadPhases: async (projectId: string) => {
        if (!projectId) return;
        try {
          const phases = (await api.getWorkflowPhases(projectId, { headers: { 'Hide-Error-Toast': 'true' } })) as unknown as PhaseInfo;
          set({ phaseInfo: phases });
        } catch (error) {
          console.error('Failed to load telemetry phases:', error);
        }
      },

      loadTasks: async (projectId: string) => {
        if (!projectId) return;
        try {
          const tasks = (await api.getTasks(projectId, { headers: { 'Hide-Error-Toast': 'true' } })) as unknown as ProjectTask[];
          set({ tasks });
        } catch (error) {
          console.error('Failed to load project tasks:', error);
        }
      },

      loadTokenUsage: async (projectId: string) => {
        if (!projectId) return;
        try {
          const usage = (await api.getProjectTokenUsage(projectId, { headers: { 'Hide-Error-Toast': 'true' } })) as unknown as TokenUsage;
          get().updateTokenUsage(usage, projectId);
        } catch (error) {
          console.error('Failed to load token usage:', error);
        }
      },

      updateTokenUsage: (usage: TokenUsage, projectId: string, taskId?: string) => {
        if (!usage || !projectId) return;

        set((state) => {
          const newTaskUsage = { ...state.taskUsage };
          const newTokenUsage = { ...state.tokenUsage };
          const safeUsage = {
            prompt_tokens: Number(usage.prompt_tokens) || 0,
            completion_tokens: Number(usage.completion_tokens) || 0,
            total_tokens: Number(usage.total_tokens) || 0
          };

          // Optional task-level mirror for debugging/inspection.
          if (taskId && typeof taskId === 'string' && taskId.trim().length > 0) {
            newTaskUsage[taskId] = {
              prompt_tokens: Math.max((newTaskUsage[taskId]?.prompt_tokens || 0), safeUsage.prompt_tokens),
              completion_tokens: Math.max((newTaskUsage[taskId]?.completion_tokens || 0), safeUsage.completion_tokens),
              total_tokens: Math.max((newTaskUsage[taskId]?.total_tokens || 0), safeUsage.total_tokens)
            };
          }

          // Cumulative usage per project.
          const currentProjectUsage = newTokenUsage[projectId] || { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 };
          newTokenUsage[projectId] = {
            prompt_tokens: Math.max(currentProjectUsage.prompt_tokens || 0, safeUsage.prompt_tokens),
            completion_tokens: Math.max(currentProjectUsage.completion_tokens || 0, safeUsage.completion_tokens),
            total_tokens: Math.max(currentProjectUsage.total_tokens || 0, safeUsage.total_tokens)
          };

          return {
            taskUsage: newTaskUsage,
            tokenUsage: newTokenUsage
          };
        });
      },

      updateLastP2PRoute: (route: { source_agent: string; target_agent: string; timestamp: number } | null) => {
        set({ lastP2PRoute: route });
      },

      setIsSyncing: (isSyncing: boolean) => {
        set({ isSyncing });
      },

      setAgentStatus: (agentId: string, status: 'idle' | 'working', currentTask?: string) => {
        set((state) => ({
          agents: state.agents.map((agent) =>
            agent.id.toLowerCase() === agentId.toLowerCase()
              ? { ...agent, status, current_task: currentTask || agent.current_task }
              : agent
          ),
        }));
      },

      refreshAgents: async () => {
        const { loadAgents } = useSystemStore.getState();
        await loadAgents();
      },

      toggleTheme: () => {
        set((state) => ({ isDark: !state.isDark }));
      }
    }),
    {
      name: 'system-storage',
      storage: createJSONStorage(() => localStorage),
      partialize: (state) => ({
        isDark: state.isDark,
      }),
    }
  )
);
