import { createHash } from 'node:crypto'
import { readdir, readFile, stat } from 'node:fs/promises'
import { join, relative, resolve, sep } from 'node:path'
import { CANONICAL_DOCUMENT_ARTIFACTS } from './types'
import { readBeeGameAssetManifestSync } from '../asset-contracts'

/** Paths owned by the workflow or generated by a build and therefore not part of implementation identity. */
export const REVISION_EXCLUDED_PREFIXES = [
  '.git/',
  '.cache/',
  '.vite/',
  '.beegame/workflow/',
  '.beegame-attachments/',
  'logs/',
  'node_modules/',
  'dist/',
  'build/',
  'out/',
  '.next/',
  'coverage/',
  'transcripts/',
] as const

function normalisePath(value: string): string {
  return value.split(sep).join('/')
}

function isExcluded(path: string): boolean {
  const candidate = `${normalisePath(path).replace(/^\/+/, '')}`
  return REVISION_EXCLUDED_PREFIXES.some(
    prefix => candidate === prefix.slice(0, -1) || candidate.startsWith(prefix),
  )
}

async function collectFiles(
  root: string,
  current: string,
  output: string[],
): Promise<void> {
  const entries = await readdir(current, { withFileTypes: true })
  for (const entry of entries) {
    const absolute = join(current, entry.name)
    const projectPath = normalisePath(relative(root, absolute))
    if (isExcluded(projectPath)) continue
    if (entry.isDirectory()) {
      await collectFiles(root, absolute, output)
    } else if (entry.isFile()) {
      output.push(projectPath)
    }
  }
}

async function digestFiles(
  root: string,
  paths: readonly string[],
  missingMarker: string,
): Promise<string> {
  const hash = createHash('sha256')
  for (const path of [...paths].sort()) {
    hash.update(path)
    hash.update('\0')
    try {
      const content = await readFile(join(root, path))
      hash.update(content)
    } catch {
      hash.update(missingMarker)
    }
    hash.update('\0')
  }
  return hash.digest('hex')
}

export async function computeDocumentRevision(
  workspacePath: string,
  confirmedBriefDigest: string,
): Promise<string> {
  const root = resolve(workspacePath)
  const digest = await digestFiles(
    root,
    CANONICAL_DOCUMENT_ARTIFACTS,
    '<missing>',
  )
  return createHash('sha256')
    .update(confirmedBriefDigest)
    .update('\0')
    .update(digest)
    .digest('hex')
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value)
}

function stableJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`
  if (!isRecord(value)) return JSON.stringify(value) ?? 'null'
  return `{${Object.keys(value)
    .sort()
    .map(key => `${JSON.stringify(key)}:${stableJson(value[key])}`)
    .join(',')}}`
}

/** Hash the complete canonical resource inventory and JSON/YAML content. */
export async function computeResourceRevision(
  workspacePath: string,
  documentRevision: string,
): Promise<string> {
  const root = resolve(workspacePath)
  let manifest: ReturnType<typeof readBeeGameAssetManifestSync> | undefined
  try {
    manifest = readBeeGameAssetManifestSync(root)
  } catch {
    // Resource preparation may start before the manifest exists.
  }
  const resourceFiles = [
    ...new Set(manifest?.resources.flatMap(value => value.file_paths) ?? []),
  ]
  const contentFiles: string[] = []
  const contentRoot = isRecord(manifest?.project_target)
    ? manifest.project_target.content_root
    : undefined
  if (typeof contentRoot === 'string')
    await collectFiles(root, join(root, contentRoot), contentFiles).catch(
      () => undefined,
    )
  const materialDigest = await digestFiles(
    root,
    [...resourceFiles, ...contentFiles],
    '<missing>',
  )
  const hash = createHash('sha256')
    .update(documentRevision)
    .update('\0')
    .update(manifest ? stableJson(manifest) : '<missing>')
    .update('\0')
    .update(materialDigest)
  return hash.digest('hex')
}

/** Hash only the canonical Manifest and its registered local resource files. */
export async function computeResourceInventoryRevision(
  workspacePath: string,
): Promise<string> {
  const root = resolve(workspacePath)
  let manifest: ReturnType<typeof readBeeGameAssetManifestSync> | undefined
  try {
    manifest = readBeeGameAssetManifestSync(root)
  } catch {
    // The resolver treats a missing or malformed Manifest as RESOURCE_PLAN.
  }
  const resourceFiles = [
    ...new Set(manifest?.resources.flatMap(value => value.file_paths) ?? []),
  ]
  const materialDigest = await digestFiles(root, resourceFiles, '<missing>')
  return createHash('sha256')
    .update(manifest ? stableJson(manifest) : '<missing>')
    .update('\0')
    .update(materialDigest)
    .digest('hex')
}

export async function computeImplementationRevision(
  workspacePath: string,
): Promise<string> {
  const root = resolve(workspacePath)
  const files: string[] = []
  try {
    await collectFiles(root, root, files)
  } catch {
    // A workspace can be created before its first authored file exists.
  }
  const implementationFiles = files.filter(path => {
    if (CANONICAL_DOCUMENT_ARTIFACTS.includes(path as never)) return false
    return !path.startsWith('docs/')
  })
  return digestFiles(root, implementationFiles, '<missing>')
}

export async function computeWorkspaceRevision(
  workspacePath: string,
): Promise<string> {
  const root = resolve(workspacePath)
  const files: string[] = []
  try {
    await collectFiles(root, root, files)
  } catch {
    // Keep an empty workspace deterministic.
  }
  return digestFiles(root, files, '<missing>')
}

export async function fileExists(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isFile()
  } catch {
    return false
  }
}

/** Resolve a workspace-relative artifact without allowing traversal outside the workspace. */
export function resolveWorkspaceRelativePath(
  workspacePath: string,
  workspaceRelativePath: string,
): string | undefined {
  if (!workspaceRelativePath.trim()) return undefined
  const root = resolve(workspacePath)
  const candidate = resolve(root, workspaceRelativePath)
  const relativePath = relative(root, candidate)
  if (
    relativePath === '' ||
    relativePath.startsWith(`..${sep}`) ||
    relativePath === '..'
  )
    return undefined
  return candidate
}

export async function workspaceFileExists(
  workspacePath: string,
  workspaceRelativePath: string,
): Promise<boolean> {
  const candidate = resolveWorkspaceRelativePath(
    workspacePath,
    workspaceRelativePath,
  )
  return candidate ? fileExists(candidate) : false
}
