import { createHash } from 'node:crypto'
import { readdir, readFile, stat } from 'node:fs/promises'
import { join, relative, resolve, sep } from 'node:path'
import { CANONICAL_DOCUMENT_ARTIFACTS } from './types'

/** Paths owned by the workflow or generated by a build and therefore not part of implementation identity. */
export const REVISION_EXCLUDED_PREFIXES = [
  '.git/',
  '.cache/',
  '.vite/',
  '.beegame/workflow/',
  '.beegame-attachments/',
  'logs/',
  'node_modules/',
  'dist/',
  'build/',
  'out/',
  '.next/',
  'coverage/',
  'transcripts/',
] as const

function normalisePath(value: string): string {
  return value.split(sep).join('/')
}

function isExcluded(path: string): boolean {
  const candidate = `${normalisePath(path).replace(/^\/+/, '')}`
  return REVISION_EXCLUDED_PREFIXES.some(
    prefix => candidate === prefix.slice(0, -1) || candidate.startsWith(prefix),
  )
}

async function collectFiles(
  root: string,
  current: string,
  output: string[],
): Promise<void> {
  const entries = await readdir(current, { withFileTypes: true })
  for (const entry of entries) {
    const absolute = join(current, entry.name)
    const projectPath = normalisePath(relative(root, absolute))
    if (isExcluded(projectPath)) continue
    if (entry.isDirectory()) {
      await collectFiles(root, absolute, output)
    } else if (entry.isFile()) {
      output.push(projectPath)
    }
  }
}

async function digestFiles(
  root: string,
  paths: readonly string[],
  missingMarker: string,
): Promise<string> {
  const hash = createHash('sha256')
  for (const path of [...paths].sort()) {
    hash.update(path)
    hash.update('\0')
    try {
      const content = await readFile(join(root, path))
      hash.update(content)
    } catch {
      hash.update(missingMarker)
    }
    hash.update('\0')
  }
  return hash.digest('hex')
}

export async function computeDocumentRevision(
  workspacePath: string,
  confirmedBriefDigest: string,
): Promise<string> {
  const root = resolve(workspacePath)
  const digest = await digestFiles(
    root,
    CANONICAL_DOCUMENT_ARTIFACTS,
    '<missing>',
  )
  return createHash('sha256')
    .update(confirmedBriefDigest)
    .update('\0')
    .update(digest)
    .digest('hex')
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value)
}

function stringArray(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter((item): item is string => typeof item === 'string')
    : []
}

function stableJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`
  if (!isRecord(value)) return JSON.stringify(value) ?? 'null'
  return `{${Object.keys(value)
    .sort()
    .map(key => `${JSON.stringify(key)}:${stableJson(value[key])}`)
    .join(',')}}`
}

/** Mutable implementation evidence does not change the approved resource selection. */
function resourceIdentityManifest(manifest: Record<string, unknown>): unknown {
  return {
    ...manifest,
    requirements: Array.isArray(manifest.requirements)
      ? manifest.requirements.map(value => {
          if (!isRecord(value)) return value
          const {
            status: _status,
            satisfied_by: _satisfiedBy,
            ...identity
          } = value
          return identity
        })
      : manifest.requirements,
    imports: Array.isArray(manifest.imports)
      ? manifest.imports.map(value => {
          if (!isRecord(value)) return value
          const {
            status: _status,
            usage_evidence: _usageEvidence,
            error: _error,
            ...identity
          } = value
          return identity
        })
      : manifest.imports,
    compositions: Array.isArray(manifest.compositions)
      ? manifest.compositions.map(value => {
          if (!isRecord(value)) return value
          const {
            status: _status,
            recipe: _recipe,
            integration_evidence: _integrationEvidence,
            ...identity
          } = value
          return identity
        })
      : manifest.compositions,
  }
}

/**
 * Resource identity is independent from source implementation identity. It
 * hashes the immutable manifest selection/plan plus the exact imported files.
 * Runtime integration status and evidence are deliberately excluded because
 * implementation updates those facts after resource approval.
 */
export async function computeResourceRevision(
  workspacePath: string,
  documentRevision: string,
): Promise<string> {
  const root = resolve(workspacePath)
  const manifestPath = 'assets/asset-manifest.json'
  let manifest: Record<string, unknown> | undefined
  try {
    const parsed = JSON.parse(await readFile(join(root, manifestPath), 'utf8'))
    if (isRecord(parsed)) manifest = parsed
  } catch {
    // Resource preparation may start before the manifest exists.
  }
  const importedFiles = Array.isArray(manifest?.imports)
    ? [
        ...new Set(
          manifest.imports.flatMap(value =>
            isRecord(value) ? stringArray(value.local_files) : [],
          ),
        ),
      ]
    : []
  const importedDigest = await digestFiles(root, importedFiles, '<missing>')
  const hash = createHash('sha256')
    .update(documentRevision)
    .update('\0')
    .update(
      manifest ? stableJson(resourceIdentityManifest(manifest)) : '<missing>',
    )
    .update('\0')
    .update(importedDigest)
  return hash.digest('hex')
}

export async function computeImplementationRevision(
  workspacePath: string,
): Promise<string> {
  const root = resolve(workspacePath)
  const files: string[] = []
  try {
    await collectFiles(root, root, files)
  } catch {
    // A workspace can be created before its first authored file exists.
  }
  const implementationFiles = files.filter(path => {
    if (CANONICAL_DOCUMENT_ARTIFACTS.includes(path as never)) return false
    return !path.startsWith('docs/')
  })
  return digestFiles(root, implementationFiles, '<missing>')
}

export async function computeWorkspaceRevision(
  workspacePath: string,
): Promise<string> {
  const root = resolve(workspacePath)
  const files: string[] = []
  try {
    await collectFiles(root, root, files)
  } catch {
    // Keep an empty workspace deterministic.
  }
  return digestFiles(root, files, '<missing>')
}

export async function fileExists(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isFile()
  } catch {
    return false
  }
}

/** Resolve a workspace-relative artifact without allowing traversal outside the workspace. */
export function resolveWorkspaceRelativePath(
  workspacePath: string,
  workspaceRelativePath: string,
): string | undefined {
  if (!workspaceRelativePath.trim()) return undefined
  const root = resolve(workspacePath)
  const candidate = resolve(root, workspaceRelativePath)
  const relativePath = relative(root, candidate)
  if (
    relativePath === '' ||
    relativePath.startsWith(`..${sep}`) ||
    relativePath === '..'
  )
    return undefined
  return candidate
}

export async function workspaceFileExists(
  workspacePath: string,
  workspaceRelativePath: string,
): Promise<boolean> {
  const candidate = resolveWorkspaceRelativePath(
    workspacePath,
    workspaceRelativePath,
  )
  return candidate ? fileExists(candidate) : false
}
