import { createHash } from 'node:crypto'
import { readdir, readFile, stat } from 'node:fs/promises'
import { join, relative, resolve, sep } from 'node:path'
import { CANONICAL_DOCUMENT_ARTIFACTS } from './types'

/** Paths owned by the workflow or generated by a build and therefore not part of implementation identity. */
export const REVISION_EXCLUDED_PREFIXES = [
  '.git/',
  '.cache/',
  '.vite/',
  '.beegame/workflow/',
  '.beegame-attachments/',
  'logs/',
  'node_modules/',
  'dist/',
  'build/',
  'out/',
  '.next/',
  'coverage/',
  'transcripts/',
] as const

function normalisePath(value: string): string {
  return value.split(sep).join('/')
}

function isExcluded(path: string): boolean {
  const candidate = `${normalisePath(path).replace(/^\/+/, '')}`
  return REVISION_EXCLUDED_PREFIXES.some(
    prefix => candidate === prefix.slice(0, -1) || candidate.startsWith(prefix),
  )
}

async function collectFiles(
  root: string,
  current: string,
  output: string[],
): Promise<void> {
  const entries = await readdir(current, { withFileTypes: true })
  for (const entry of entries) {
    const absolute = join(current, entry.name)
    const projectPath = normalisePath(relative(root, absolute))
    if (isExcluded(projectPath)) continue
    if (entry.isDirectory()) {
      await collectFiles(root, absolute, output)
    } else if (entry.isFile()) {
      output.push(projectPath)
    }
  }
}

async function digestFiles(
  root: string,
  paths: readonly string[],
  missingMarker: string,
): Promise<string> {
  const hash = createHash('sha256')
  for (const path of [...paths].sort()) {
    hash.update(path)
    hash.update('\0')
    try {
      const content = await readFile(join(root, path))
      hash.update(content)
    } catch {
      hash.update(missingMarker)
    }
    hash.update('\0')
  }
  return hash.digest('hex')
}

export async function computeDocumentRevision(
  workspacePath: string,
  confirmedBriefDigest: string,
): Promise<string> {
  const root = resolve(workspacePath)
  const digest = await digestFiles(
    root,
    CANONICAL_DOCUMENT_ARTIFACTS,
    '<missing>',
  )
  return createHash('sha256')
    .update(confirmedBriefDigest)
    .update('\0')
    .update(digest)
    .digest('hex')
}

/**
 * Resource identity is independent from source implementation identity. It
 * includes the manifest and every file under assets so a changed import or
 * binding invalidates the task plan that consumed it.
 */
export async function computeResourceRevision(
  workspacePath: string,
  documentRevision: string,
): Promise<string> {
  const root = resolve(workspacePath)
  const files: string[] = []
  try {
    await collectFiles(root, root, files)
  } catch {
    // Resource preparation may start before an assets directory exists.
  }
  const resourceFiles = files.filter(
    path => path === 'assets' || path.startsWith('assets/'),
  )
  const digest = await digestFiles(root, resourceFiles, '<missing>')
  return createHash('sha256')
    .update(documentRevision)
    .update('\0')
    .update(digest)
    .digest('hex')
}

export async function computeImplementationRevision(
  workspacePath: string,
): Promise<string> {
  const root = resolve(workspacePath)
  const files: string[] = []
  try {
    await collectFiles(root, root, files)
  } catch {
    // A workspace can be created before its first authored file exists.
  }
  const implementationFiles = files.filter(path => {
    if (CANONICAL_DOCUMENT_ARTIFACTS.includes(path as never)) return false
    return !path.startsWith('docs/')
  })
  return digestFiles(root, implementationFiles, '<missing>')
}

export async function computeWorkspaceRevision(
  workspacePath: string,
): Promise<string> {
  const root = resolve(workspacePath)
  const files: string[] = []
  try {
    await collectFiles(root, root, files)
  } catch {
    // Keep an empty workspace deterministic.
  }
  return digestFiles(root, files, '<missing>')
}

export async function fileExists(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isFile()
  } catch {
    return false
  }
}

/** Resolve a workspace-relative artifact without allowing traversal outside the workspace. */
export function resolveWorkspaceRelativePath(
  workspacePath: string,
  workspaceRelativePath: string,
): string | undefined {
  if (!workspaceRelativePath.trim()) return undefined
  const root = resolve(workspacePath)
  const candidate = resolve(root, workspaceRelativePath)
  const relativePath = relative(root, candidate)
  if (
    relativePath === '' ||
    relativePath.startsWith(`..${sep}`) ||
    relativePath === '..'
  )
    return undefined
  return candidate
}

export async function workspaceFileExists(
  workspacePath: string,
  workspaceRelativePath: string,
): Promise<boolean> {
  const candidate = resolveWorkspaceRelativePath(
    workspacePath,
    workspaceRelativePath,
  )
  return candidate ? fileExists(candidate) : false
}
